"""base structure

Revision ID: 05c12f3cb8f7
Revises: 
Create Date: 2025-05-14 16:57:14.412033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c12f3cb8f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('actions',
    sa.Column('action_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('TEXT_MESSAGE', 'IMAGE_MESSAGE', name='actiontype'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id'),
    sa.UniqueConstraint('action_id', 'sequence_number')
    )
    op.create_table('buttons',
    sa.Column('button_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.String(length=64), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('destination_group_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['destination_group_id'], ['groups.group_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('button_id'),
    sa.UniqueConstraint('group_id', 'sequence_number')
    )
    op.create_table('inputs',
    sa.Column('input_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.Enum('INT', 'EMAIL', 'PHONE_NUMBER', 'ANY', name='inputtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('destination_group_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['destination_group_id'], ['groups.group_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('input_id'),
    sa.UniqueConstraint('group_id', 'type')
    )
    op.create_table('image_message_actions',
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('image_path', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.action_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('text_message_actions',
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.action_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_message_actions')
    op.drop_table('image_message_actions')
    op.drop_table('inputs')
    op.drop_table('buttons')
    op.drop_table('actions')
    op.drop_table('groups')
    op.drop_table('projects')
    op.execute('DROP TYPE inputtype;')
    op.execute('DROP TYPE actiontype;')
    # ### end Alembic commands ###
